// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/proto/sentinel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Risk level enum
type RiskLevel int32

const (
	RiskLevel_RISK_UNKNOWN  RiskLevel = 0
	RiskLevel_RISK_SAFE     RiskLevel = 1
	RiskLevel_RISK_LOW      RiskLevel = 2
	RiskLevel_RISK_MEDIUM   RiskLevel = 3
	RiskLevel_RISK_HIGH     RiskLevel = 4
	RiskLevel_RISK_CRITICAL RiskLevel = 5
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_UNKNOWN",
		1: "RISK_SAFE",
		2: "RISK_LOW",
		3: "RISK_MEDIUM",
		4: "RISK_HIGH",
		5: "RISK_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_UNKNOWN":  0,
		"RISK_SAFE":     1,
		"RISK_LOW":      2,
		"RISK_MEDIUM":   3,
		"RISK_HIGH":     4,
		"RISK_CRITICAL": 5,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_sentinel_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_pkg_proto_sentinel_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

// Recommended action
type Recommendation int32

const (
	Recommendation_RECOMMENDATION_UNKNOWN Recommendation = 0
	Recommendation_RECOMMENDATION_ALLOW   Recommendation = 1
	Recommendation_RECOMMENDATION_FLAG    Recommendation = 2 // Log and monitor
	Recommendation_RECOMMENDATION_REVIEW  Recommendation = 3 // Human review needed
	Recommendation_RECOMMENDATION_BLOCK   Recommendation = 4 // Trigger pause
)

// Enum value maps for Recommendation.
var (
	Recommendation_name = map[int32]string{
		0: "RECOMMENDATION_UNKNOWN",
		1: "RECOMMENDATION_ALLOW",
		2: "RECOMMENDATION_FLAG",
		3: "RECOMMENDATION_REVIEW",
		4: "RECOMMENDATION_BLOCK",
	}
	Recommendation_value = map[string]int32{
		"RECOMMENDATION_UNKNOWN": 0,
		"RECOMMENDATION_ALLOW":   1,
		"RECOMMENDATION_FLAG":    2,
		"RECOMMENDATION_REVIEW":  3,
		"RECOMMENDATION_BLOCK":   4,
	}
)

func (x Recommendation) Enum() *Recommendation {
	p := new(Recommendation)
	*p = x
	return p
}

func (x Recommendation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Recommendation) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_sentinel_proto_enumTypes[1].Descriptor()
}

func (Recommendation) Type() protoreflect.EnumType {
	return &file_pkg_proto_sentinel_proto_enumTypes[1]
}

func (x Recommendation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Recommendation.Descriptor instead.
func (Recommendation) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

// Request to analyze a single transaction
type AnalyzeRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TxHash      string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	FromAddress string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress   string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"` // Empty for contract creation
	Value       string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                          // Wei as string (big number)
	Gas         uint64                 `protobuf:"varint,5,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice    string                 `protobuf:"bytes,6,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"` // Wei as string
	InputData   []byte                 `protobuf:"bytes,7,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Nonce       uint64                 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId     uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Optional: simulation results if already simulated
	Simulation    *SimulationResult `protobuf:"bytes,10,opt,name=simulation,proto3" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AnalyzeRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *AnalyzeRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *AnalyzeRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AnalyzeRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *AnalyzeRequest) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *AnalyzeRequest) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *AnalyzeRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *AnalyzeRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *AnalyzeRequest) GetSimulation() *SimulationResult {
	if x != nil {
		return x.Simulation
	}
	return nil
}

// Pre-computed simulation result
type SimulationResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GasUsed        uint64                 `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	StorageChanges []*StorageChange       `protobuf:"bytes,3,rep,name=storage_changes,json=storageChanges,proto3" json:"storage_changes,omitempty"`
	CallTraces     []*CallTrace           `protobuf:"bytes,4,rep,name=call_traces,json=callTraces,proto3" json:"call_traces,omitempty"`
	Logs           []string               `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationResult) Reset() {
	*x = SimulationResult{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResult) ProtoMessage() {}

func (x *SimulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResult.ProtoReflect.Descriptor instead.
func (*SimulationResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulationResult) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *SimulationResult) GetStorageChanges() []*StorageChange {
	if x != nil {
		return x.StorageChanges
	}
	return nil
}

func (x *SimulationResult) GetCallTraces() []*CallTrace {
	if x != nil {
		return x.CallTraces
	}
	return nil
}

func (x *SimulationResult) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

// Storage change from simulation
type StorageChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      string                 `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Slot          string                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      string                 `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageChange) Reset() {
	*x = StorageChange{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageChange) ProtoMessage() {}

func (x *StorageChange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageChange.ProtoReflect.Descriptor instead.
func (*StorageChange) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *StorageChange) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *StorageChange) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *StorageChange) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *StorageChange) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

// Call trace from simulation
type CallTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallType      string                 `protobuf:"bytes,1,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"` // CALL, DELEGATECALL, STATICCALL, CREATE, CREATE2
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Input         []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Output        []byte                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Gas           uint64                 `protobuf:"varint,7,opt,name=gas,proto3" json:"gas,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,8,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Depth         uint32                 `protobuf:"varint,9,opt,name=depth,proto3" json:"depth,omitempty"`
	Error         bool                   `protobuf:"varint,10,opt,name=error,proto3" json:"error,omitempty"`
	Calls         []*CallTrace           `protobuf:"bytes,11,rep,name=calls,proto3" json:"calls,omitempty"` // Nested calls
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTrace) Reset() {
	*x = CallTrace{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTrace) ProtoMessage() {}

func (x *CallTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTrace.ProtoReflect.Descriptor instead.
func (*CallTrace) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *CallTrace) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *CallTrace) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CallTrace) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CallTrace) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CallTrace) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CallTrace) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CallTrace) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *CallTrace) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *CallTrace) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *CallTrace) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *CallTrace) GetCalls() []*CallTrace {
	if x != nil {
		return x.Calls
	}
	return nil
}

// Response from transaction analysis
type AnalyzeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TxHash         string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	IsSuspicious   bool                   `protobuf:"varint,2,opt,name=is_suspicious,json=isSuspicious,proto3" json:"is_suspicious,omitempty"`
	AnomalyScore   float64                `protobuf:"fixed64,3,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"` // 0.0 - 1.0
	Confidence     float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`                         // 0.0 - 1.0
	RiskLevel      RiskLevel              `protobuf:"varint,5,opt,name=risk_level,json=riskLevel,proto3,enum=sentinel.RiskLevel" json:"risk_level,omitempty"`
	RiskIndicators []string               `protobuf:"bytes,6,rep,name=risk_indicators,json=riskIndicators,proto3" json:"risk_indicators,omitempty"`
	Recommendation Recommendation         `protobuf:"varint,7,opt,name=recommendation,proto3,enum=sentinel.Recommendation" json:"recommendation,omitempty"`
	LatencyMs      float64                `protobuf:"fixed64,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Detailed breakdown
	ProtocolContext *ProtocolContext  `protobuf:"bytes,9,opt,name=protocol_context,json=protocolContext,proto3" json:"protocol_context,omitempty"`
	Features        *FeatureBreakdown `protobuf:"bytes,10,opt,name=features,proto3" json:"features,omitempty"`
	Explanation     string            `protobuf:"bytes,11,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AnalyzeResponse) GetIsSuspicious() bool {
	if x != nil {
		return x.IsSuspicious
	}
	return false
}

func (x *AnalyzeResponse) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *AnalyzeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeResponse) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_UNKNOWN
}

func (x *AnalyzeResponse) GetRiskIndicators() []string {
	if x != nil {
		return x.RiskIndicators
	}
	return nil
}

func (x *AnalyzeResponse) GetRecommendation() Recommendation {
	if x != nil {
		return x.Recommendation
	}
	return Recommendation_RECOMMENDATION_UNKNOWN
}

func (x *AnalyzeResponse) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AnalyzeResponse) GetProtocolContext() *ProtocolContext {
	if x != nil {
		return x.ProtocolContext
	}
	return nil
}

func (x *AnalyzeResponse) GetFeatures() *FeatureBreakdown {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *AnalyzeResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// Protocol context from protocol filter
type ProtocolContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Protocol         string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`   // e.g., "uniswap_v2", "aave_v3"
	Operation        string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // e.g., "swap", "borrow", "liquidate"
	IsKnownProtocol  bool                   `protobuf:"varint,3,opt,name=is_known_protocol,json=isKnownProtocol,proto3" json:"is_known_protocol,omitempty"`
	IsKnownOperation bool                   `protobuf:"varint,4,opt,name=is_known_operation,json=isKnownOperation,proto3" json:"is_known_operation,omitempty"`
	WithinBounds     bool                   `protobuf:"varint,5,opt,name=within_bounds,json=withinBounds,proto3" json:"within_bounds,omitempty"`
	BoundViolations  []string               `protobuf:"bytes,6,rep,name=bound_violations,json=boundViolations,proto3" json:"bound_violations,omitempty"`
	RiskAdjustment   float64                `protobuf:"fixed64,7,opt,name=risk_adjustment,json=riskAdjustment,proto3" json:"risk_adjustment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtocolContext) Reset() {
	*x = ProtocolContext{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolContext) ProtoMessage() {}

func (x *ProtocolContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolContext.ProtoReflect.Descriptor instead.
func (*ProtocolContext) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *ProtocolContext) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolContext) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ProtocolContext) GetIsKnownProtocol() bool {
	if x != nil {
		return x.IsKnownProtocol
	}
	return false
}

func (x *ProtocolContext) GetIsKnownOperation() bool {
	if x != nil {
		return x.IsKnownOperation
	}
	return false
}

func (x *ProtocolContext) GetWithinBounds() bool {
	if x != nil {
		return x.WithinBounds
	}
	return false
}

func (x *ProtocolContext) GetBoundViolations() []string {
	if x != nil {
		return x.BoundViolations
	}
	return nil
}

func (x *ProtocolContext) GetRiskAdjustment() float64 {
	if x != nil {
		return x.RiskAdjustment
	}
	return 0
}

// Feature breakdown for explainability
type FeatureBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlashLoan     *FlashLoanFeatures     `protobuf:"bytes,1,opt,name=flash_loan,json=flashLoan,proto3" json:"flash_loan,omitempty"`
	StateVariance *StateVarianceFeatures `protobuf:"bytes,2,opt,name=state_variance,json=stateVariance,proto3" json:"state_variance,omitempty"`
	Bytecode      *BytecodeFeatures      `protobuf:"bytes,3,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	Opcode        *OpcodeFeatures        `protobuf:"bytes,4,opt,name=opcode,proto3" json:"opcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureBreakdown) Reset() {
	*x = FeatureBreakdown{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureBreakdown) ProtoMessage() {}

func (x *FeatureBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureBreakdown.ProtoReflect.Descriptor instead.
func (*FeatureBreakdown) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *FeatureBreakdown) GetFlashLoan() *FlashLoanFeatures {
	if x != nil {
		return x.FlashLoan
	}
	return nil
}

func (x *FeatureBreakdown) GetStateVariance() *StateVarianceFeatures {
	if x != nil {
		return x.StateVariance
	}
	return nil
}

func (x *FeatureBreakdown) GetBytecode() *BytecodeFeatures {
	if x != nil {
		return x.Bytecode
	}
	return nil
}

func (x *FeatureBreakdown) GetOpcode() *OpcodeFeatures {
	if x != nil {
		return x.Opcode
	}
	return nil
}

type FlashLoanFeatures struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasFlashLoan      bool                   `protobuf:"varint,1,opt,name=has_flash_loan,json=hasFlashLoan,proto3" json:"has_flash_loan,omitempty"`
	FlashLoanCount    int32                  `protobuf:"varint,2,opt,name=flash_loan_count,json=flashLoanCount,proto3" json:"flash_loan_count,omitempty"`
	Providers         []string               `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	TotalBorrowed     string                 `protobuf:"bytes,4,opt,name=total_borrowed,json=totalBorrowed,proto3" json:"total_borrowed,omitempty"` // Wei as string
	HasCallback       bool                   `protobuf:"varint,5,opt,name=has_callback,json=hasCallback,proto3" json:"has_callback,omitempty"`
	NestedFlashLoans  bool                   `protobuf:"varint,6,opt,name=nested_flash_loans,json=nestedFlashLoans,proto3" json:"nested_flash_loans,omitempty"`
	RepaymentDetected bool                   `protobuf:"varint,7,opt,name=repayment_detected,json=repaymentDetected,proto3" json:"repayment_detected,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FlashLoanFeatures) Reset() {
	*x = FlashLoanFeatures{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashLoanFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashLoanFeatures) ProtoMessage() {}

func (x *FlashLoanFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashLoanFeatures.ProtoReflect.Descriptor instead.
func (*FlashLoanFeatures) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{7}
}

func (x *FlashLoanFeatures) GetHasFlashLoan() bool {
	if x != nil {
		return x.HasFlashLoan
	}
	return false
}

func (x *FlashLoanFeatures) GetFlashLoanCount() int32 {
	if x != nil {
		return x.FlashLoanCount
	}
	return 0
}

func (x *FlashLoanFeatures) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *FlashLoanFeatures) GetTotalBorrowed() string {
	if x != nil {
		return x.TotalBorrowed
	}
	return ""
}

func (x *FlashLoanFeatures) GetHasCallback() bool {
	if x != nil {
		return x.HasCallback
	}
	return false
}

func (x *FlashLoanFeatures) GetNestedFlashLoans() bool {
	if x != nil {
		return x.NestedFlashLoans
	}
	return false
}

func (x *FlashLoanFeatures) GetRepaymentDetected() bool {
	if x != nil {
		return x.RepaymentDetected
	}
	return false
}

type StateVarianceFeatures struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TotalStorageChanges     int32                  `protobuf:"varint,1,opt,name=total_storage_changes,json=totalStorageChanges,proto3" json:"total_storage_changes,omitempty"`
	UniqueContractsModified int32                  `protobuf:"varint,2,opt,name=unique_contracts_modified,json=uniqueContractsModified,proto3" json:"unique_contracts_modified,omitempty"`
	UniqueSlotsModified     int32                  `protobuf:"varint,3,opt,name=unique_slots_modified,json=uniqueSlotsModified,proto3" json:"unique_slots_modified,omitempty"`
	BalanceSlotChanges      int32                  `protobuf:"varint,4,opt,name=balance_slot_changes,json=balanceSlotChanges,proto3" json:"balance_slot_changes,omitempty"`
	LargeValueChanges       int32                  `protobuf:"varint,5,opt,name=large_value_changes,json=largeValueChanges,proto3" json:"large_value_changes,omitempty"`
	MaxValueDelta           string                 `protobuf:"bytes,6,opt,name=max_value_delta,json=maxValueDelta,proto3" json:"max_value_delta,omitempty"` // Wei as string
	VarianceRatio           float64                `protobuf:"fixed64,7,opt,name=variance_ratio,json=varianceRatio,proto3" json:"variance_ratio,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StateVarianceFeatures) Reset() {
	*x = StateVarianceFeatures{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateVarianceFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateVarianceFeatures) ProtoMessage() {}

func (x *StateVarianceFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateVarianceFeatures.ProtoReflect.Descriptor instead.
func (*StateVarianceFeatures) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{8}
}

func (x *StateVarianceFeatures) GetTotalStorageChanges() int32 {
	if x != nil {
		return x.TotalStorageChanges
	}
	return 0
}

func (x *StateVarianceFeatures) GetUniqueContractsModified() int32 {
	if x != nil {
		return x.UniqueContractsModified
	}
	return 0
}

func (x *StateVarianceFeatures) GetUniqueSlotsModified() int32 {
	if x != nil {
		return x.UniqueSlotsModified
	}
	return 0
}

func (x *StateVarianceFeatures) GetBalanceSlotChanges() int32 {
	if x != nil {
		return x.BalanceSlotChanges
	}
	return 0
}

func (x *StateVarianceFeatures) GetLargeValueChanges() int32 {
	if x != nil {
		return x.LargeValueChanges
	}
	return 0
}

func (x *StateVarianceFeatures) GetMaxValueDelta() string {
	if x != nil {
		return x.MaxValueDelta
	}
	return ""
}

func (x *StateVarianceFeatures) GetVarianceRatio() float64 {
	if x != nil {
		return x.VarianceRatio
	}
	return 0
}

type BytecodeFeatures struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BytecodeLength      int32                  `protobuf:"varint,1,opt,name=bytecode_length,json=bytecodeLength,proto3" json:"bytecode_length,omitempty"`
	IsContract          bool                   `protobuf:"varint,2,opt,name=is_contract,json=isContract,proto3" json:"is_contract,omitempty"`
	IsProxy             bool                   `protobuf:"varint,3,opt,name=is_proxy,json=isProxy,proto3" json:"is_proxy,omitempty"`
	ProxyType           string                 `protobuf:"bytes,4,opt,name=proxy_type,json=proxyType,proto3" json:"proxy_type,omitempty"`
	ContractAgeBlocks   int32                  `protobuf:"varint,5,opt,name=contract_age_blocks,json=contractAgeBlocks,proto3" json:"contract_age_blocks,omitempty"`
	IsVerified          bool                   `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	MatchesKnownExploit bool                   `protobuf:"varint,7,opt,name=matches_known_exploit,json=matchesKnownExploit,proto3" json:"matches_known_exploit,omitempty"`
	MatchedExploitId    string                 `protobuf:"bytes,8,opt,name=matched_exploit_id,json=matchedExploitId,proto3" json:"matched_exploit_id,omitempty"`
	JaccardSimilarity   float64                `protobuf:"fixed64,9,opt,name=jaccard_similarity,json=jaccardSimilarity,proto3" json:"jaccard_similarity,omitempty"`
	HasSelfdestruct     bool                   `protobuf:"varint,10,opt,name=has_selfdestruct,json=hasSelfdestruct,proto3" json:"has_selfdestruct,omitempty"`
	HasDelegatecall     bool                   `protobuf:"varint,11,opt,name=has_delegatecall,json=hasDelegatecall,proto3" json:"has_delegatecall,omitempty"`
	HasCreate2          bool                   `protobuf:"varint,12,opt,name=has_create2,json=hasCreate2,proto3" json:"has_create2,omitempty"`
	UniqueOpcodes       int32                  `protobuf:"varint,13,opt,name=unique_opcodes,json=uniqueOpcodes,proto3" json:"unique_opcodes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BytecodeFeatures) Reset() {
	*x = BytecodeFeatures{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytecodeFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytecodeFeatures) ProtoMessage() {}

func (x *BytecodeFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytecodeFeatures.ProtoReflect.Descriptor instead.
func (*BytecodeFeatures) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{9}
}

func (x *BytecodeFeatures) GetBytecodeLength() int32 {
	if x != nil {
		return x.BytecodeLength
	}
	return 0
}

func (x *BytecodeFeatures) GetIsContract() bool {
	if x != nil {
		return x.IsContract
	}
	return false
}

func (x *BytecodeFeatures) GetIsProxy() bool {
	if x != nil {
		return x.IsProxy
	}
	return false
}

func (x *BytecodeFeatures) GetProxyType() string {
	if x != nil {
		return x.ProxyType
	}
	return ""
}

func (x *BytecodeFeatures) GetContractAgeBlocks() int32 {
	if x != nil {
		return x.ContractAgeBlocks
	}
	return 0
}

func (x *BytecodeFeatures) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *BytecodeFeatures) GetMatchesKnownExploit() bool {
	if x != nil {
		return x.MatchesKnownExploit
	}
	return false
}

func (x *BytecodeFeatures) GetMatchedExploitId() string {
	if x != nil {
		return x.MatchedExploitId
	}
	return ""
}

func (x *BytecodeFeatures) GetJaccardSimilarity() float64 {
	if x != nil {
		return x.JaccardSimilarity
	}
	return 0
}

func (x *BytecodeFeatures) GetHasSelfdestruct() bool {
	if x != nil {
		return x.HasSelfdestruct
	}
	return false
}

func (x *BytecodeFeatures) GetHasDelegatecall() bool {
	if x != nil {
		return x.HasDelegatecall
	}
	return false
}

func (x *BytecodeFeatures) GetHasCreate2() bool {
	if x != nil {
		return x.HasCreate2
	}
	return false
}

func (x *BytecodeFeatures) GetUniqueOpcodes() int32 {
	if x != nil {
		return x.UniqueOpcodes
	}
	return 0
}

type OpcodeFeatures struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalCalls        int32                  `protobuf:"varint,1,opt,name=total_calls,json=totalCalls,proto3" json:"total_calls,omitempty"`
	CallDepth         int32                  `protobuf:"varint,2,opt,name=call_depth,json=callDepth,proto3" json:"call_depth,omitempty"`
	DelegatecallCount int32                  `protobuf:"varint,3,opt,name=delegatecall_count,json=delegatecallCount,proto3" json:"delegatecall_count,omitempty"`
	StaticcallCount   int32                  `protobuf:"varint,4,opt,name=staticcall_count,json=staticcallCount,proto3" json:"staticcall_count,omitempty"`
	CreateCount       int32                  `protobuf:"varint,5,opt,name=create_count,json=createCount,proto3" json:"create_count,omitempty"`
	Create2Count      int32                  `protobuf:"varint,6,opt,name=create2_count,json=create2Count,proto3" json:"create2_count,omitempty"`
	SelfdestructCount int32                  `protobuf:"varint,7,opt,name=selfdestruct_count,json=selfdestructCount,proto3" json:"selfdestruct_count,omitempty"`
	InternalCalls     int32                  `protobuf:"varint,8,opt,name=internal_calls,json=internalCalls,proto3" json:"internal_calls,omitempty"`
	ExternalCalls     int32                  `protobuf:"varint,9,opt,name=external_calls,json=externalCalls,proto3" json:"external_calls,omitempty"`
	GasForwardedRatio float64                `protobuf:"fixed64,10,opt,name=gas_forwarded_ratio,json=gasForwardedRatio,proto3" json:"gas_forwarded_ratio,omitempty"`
	RevertCount       int32                  `protobuf:"varint,11,opt,name=revert_count,json=revertCount,proto3" json:"revert_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OpcodeFeatures) Reset() {
	*x = OpcodeFeatures{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpcodeFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpcodeFeatures) ProtoMessage() {}

func (x *OpcodeFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpcodeFeatures.ProtoReflect.Descriptor instead.
func (*OpcodeFeatures) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{10}
}

func (x *OpcodeFeatures) GetTotalCalls() int32 {
	if x != nil {
		return x.TotalCalls
	}
	return 0
}

func (x *OpcodeFeatures) GetCallDepth() int32 {
	if x != nil {
		return x.CallDepth
	}
	return 0
}

func (x *OpcodeFeatures) GetDelegatecallCount() int32 {
	if x != nil {
		return x.DelegatecallCount
	}
	return 0
}

func (x *OpcodeFeatures) GetStaticcallCount() int32 {
	if x != nil {
		return x.StaticcallCount
	}
	return 0
}

func (x *OpcodeFeatures) GetCreateCount() int32 {
	if x != nil {
		return x.CreateCount
	}
	return 0
}

func (x *OpcodeFeatures) GetCreate2Count() int32 {
	if x != nil {
		return x.Create2Count
	}
	return 0
}

func (x *OpcodeFeatures) GetSelfdestructCount() int32 {
	if x != nil {
		return x.SelfdestructCount
	}
	return 0
}

func (x *OpcodeFeatures) GetInternalCalls() int32 {
	if x != nil {
		return x.InternalCalls
	}
	return 0
}

func (x *OpcodeFeatures) GetExternalCalls() int32 {
	if x != nil {
		return x.ExternalCalls
	}
	return 0
}

func (x *OpcodeFeatures) GetGasForwardedRatio() float64 {
	if x != nil {
		return x.GasForwardedRatio
	}
	return 0
}

func (x *OpcodeFeatures) GetRevertCount() int32 {
	if x != nil {
		return x.RevertCount
	}
	return 0
}

// Batch request
type AnalyzeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*AnalyzeRequest      `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBatchRequest) Reset() {
	*x = AnalyzeBatchRequest{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBatchRequest) ProtoMessage() {}

func (x *AnalyzeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBatchRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{11}
}

func (x *AnalyzeBatchRequest) GetTransactions() []*AnalyzeRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Batch response
type AnalyzeBatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*AnalyzeResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalLatencyMs float64                `protobuf:"fixed64,2,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeBatchResponse) Reset() {
	*x = AnalyzeBatchResponse{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBatchResponse) ProtoMessage() {}

func (x *AnalyzeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBatchResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{12}
}

func (x *AnalyzeBatchResponse) GetResults() []*AnalyzeResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *AnalyzeBatchResponse) GetTotalLatencyMs() float64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

// Health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ModelLoadedAt string                 `protobuf:"bytes,3,opt,name=model_loaded_at,json=modelLoadedAt,proto3" json:"model_loaded_at,omitempty"`
	RpcConnected  bool                   `protobuf:"varint,4,opt,name=rpc_connected,json=rpcConnected,proto3" json:"rpc_connected,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetModelLoadedAt() string {
	if x != nil {
		return x.ModelLoadedAt
	}
	return ""
}

func (x *HealthResponse) GetRpcConnected() bool {
	if x != nil {
		return x.RpcConnected
	}
	return false
}

func (x *HealthResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

// Statistics request
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{15}
}

// Statistics response
type StatsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TransactionsAnalyzed uint64                 `protobuf:"varint,1,opt,name=transactions_analyzed,json=transactionsAnalyzed,proto3" json:"transactions_analyzed,omitempty"`
	SuspiciousDetected   uint64                 `protobuf:"varint,2,opt,name=suspicious_detected,json=suspiciousDetected,proto3" json:"suspicious_detected,omitempty"`
	BlockedRecommended   uint64                 `protobuf:"varint,3,opt,name=blocked_recommended,json=blockedRecommended,proto3" json:"blocked_recommended,omitempty"`
	AverageLatencyMs     float64                `protobuf:"fixed64,4,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	ModelAccuracy        float64                `protobuf:"fixed64,5,opt,name=model_accuracy,json=modelAccuracy,proto3" json:"model_accuracy,omitempty"`
	FalsePositiveRate    float64                `protobuf:"fixed64,6,opt,name=false_positive_rate,json=falsePositiveRate,proto3" json:"false_positive_rate,omitempty"`
	// Breakdown by risk level
	ByRiskLevel map[string]uint64 `protobuf:"bytes,7,rep,name=by_risk_level,json=byRiskLevel,proto3" json:"by_risk_level,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Breakdown by protocol
	ByProtocol map[string]uint64 `protobuf:"bytes,8,rep,name=by_protocol,json=byProtocol,proto3" json:"by_protocol,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Recent alerts
	RecentAlerts  []*RecentAlert `protobuf:"bytes,9,rep,name=recent_alerts,json=recentAlerts,proto3" json:"recent_alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{16}
}

func (x *StatsResponse) GetTransactionsAnalyzed() uint64 {
	if x != nil {
		return x.TransactionsAnalyzed
	}
	return 0
}

func (x *StatsResponse) GetSuspiciousDetected() uint64 {
	if x != nil {
		return x.SuspiciousDetected
	}
	return 0
}

func (x *StatsResponse) GetBlockedRecommended() uint64 {
	if x != nil {
		return x.BlockedRecommended
	}
	return 0
}

func (x *StatsResponse) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *StatsResponse) GetModelAccuracy() float64 {
	if x != nil {
		return x.ModelAccuracy
	}
	return 0
}

func (x *StatsResponse) GetFalsePositiveRate() float64 {
	if x != nil {
		return x.FalsePositiveRate
	}
	return 0
}

func (x *StatsResponse) GetByRiskLevel() map[string]uint64 {
	if x != nil {
		return x.ByRiskLevel
	}
	return nil
}

func (x *StatsResponse) GetByProtocol() map[string]uint64 {
	if x != nil {
		return x.ByProtocol
	}
	return nil
}

func (x *StatsResponse) GetRecentAlerts() []*RecentAlert {
	if x != nil {
		return x.RecentAlerts
	}
	return nil
}

type RecentAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TxHash         string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	RiskLevel      RiskLevel              `protobuf:"varint,2,opt,name=risk_level,json=riskLevel,proto3,enum=sentinel.RiskLevel" json:"risk_level,omitempty"`
	Timestamp      string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Protocol       string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	RiskIndicators []string               `protobuf:"bytes,5,rep,name=risk_indicators,json=riskIndicators,proto3" json:"risk_indicators,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecentAlert) Reset() {
	*x = RecentAlert{}
	mi := &file_pkg_proto_sentinel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentAlert) ProtoMessage() {}

func (x *RecentAlert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_sentinel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentAlert.ProtoReflect.Descriptor instead.
func (*RecentAlert) Descriptor() ([]byte, []int) {
	return file_pkg_proto_sentinel_proto_rawDescGZIP(), []int{17}
}

func (x *RecentAlert) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *RecentAlert) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_UNKNOWN
}

func (x *RecentAlert) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RecentAlert) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RecentAlert) GetRiskIndicators() []string {
	if x != nil {
		return x.RiskIndicators
	}
	return nil
}

var File_pkg_proto_sentinel_proto protoreflect.FileDescriptor

const file_pkg_proto_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/sentinel.proto\x12\bsentinel\"\xbc\x02\n" +
	"\x0eAnalyzeRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x10\n" +
	"\x03gas\x18\x05 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\x06 \x01(\tR\bgasPrice\x12\x1d\n" +
	"\n" +
	"input_data\x18\a \x01(\fR\tinputData\x12\x14\n" +
	"\x05nonce\x18\b \x01(\x04R\x05nonce\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\x12:\n" +
	"\n" +
	"simulation\x18\n" +
	" \x01(\v2\x1a.sentinel.SimulationResultR\n" +
	"simulation\"\xd3\x01\n" +
	"\x10SimulationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bgas_used\x18\x02 \x01(\x04R\agasUsed\x12@\n" +
	"\x0fstorage_changes\x18\x03 \x03(\v2\x17.sentinel.StorageChangeR\x0estorageChanges\x124\n" +
	"\vcall_traces\x18\x04 \x03(\v2\x13.sentinel.CallTraceR\n" +
	"callTraces\x12\x12\n" +
	"\x04logs\x18\x05 \x03(\tR\x04logs\"y\n" +
	"\rStorageChange\x12\x1a\n" +
	"\bcontract\x18\x01 \x01(\tR\bcontract\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\tR\x04slot\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x04 \x01(\tR\bnewValue\"\x94\x02\n" +
	"\tCallTrace\x12\x1b\n" +
	"\tcall_type\x18\x01 \x01(\tR\bcallType\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\x12\x16\n" +
	"\x06output\x18\x06 \x01(\fR\x06output\x12\x10\n" +
	"\x03gas\x18\a \x01(\x04R\x03gas\x12\x19\n" +
	"\bgas_used\x18\b \x01(\x04R\agasUsed\x12\x14\n" +
	"\x05depth\x18\t \x01(\rR\x05depth\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\bR\x05error\x12)\n" +
	"\x05calls\x18\v \x03(\v2\x13.sentinel.CallTraceR\x05calls\"\xf2\x03\n" +
	"\x0fAnalyzeResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12#\n" +
	"\ris_suspicious\x18\x02 \x01(\bR\fisSuspicious\x12#\n" +
	"\ranomaly_score\x18\x03 \x01(\x01R\fanomalyScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x122\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\x0e2\x13.sentinel.RiskLevelR\triskLevel\x12'\n" +
	"\x0frisk_indicators\x18\x06 \x03(\tR\x0eriskIndicators\x12@\n" +
	"\x0erecommendation\x18\a \x01(\x0e2\x18.sentinel.RecommendationR\x0erecommendation\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x01R\tlatencyMs\x12D\n" +
	"\x10protocol_context\x18\t \x01(\v2\x19.sentinel.ProtocolContextR\x0fprotocolContext\x126\n" +
	"\bfeatures\x18\n" +
	" \x01(\v2\x1a.sentinel.FeatureBreakdownR\bfeatures\x12 \n" +
	"\vexplanation\x18\v \x01(\tR\vexplanation\"\x9e\x02\n" +
	"\x0fProtocolContext\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12*\n" +
	"\x11is_known_protocol\x18\x03 \x01(\bR\x0fisKnownProtocol\x12,\n" +
	"\x12is_known_operation\x18\x04 \x01(\bR\x10isKnownOperation\x12#\n" +
	"\rwithin_bounds\x18\x05 \x01(\bR\fwithinBounds\x12)\n" +
	"\x10bound_violations\x18\x06 \x03(\tR\x0fboundViolations\x12'\n" +
	"\x0frisk_adjustment\x18\a \x01(\x01R\x0eriskAdjustment\"\x80\x02\n" +
	"\x10FeatureBreakdown\x12:\n" +
	"\n" +
	"flash_loan\x18\x01 \x01(\v2\x1b.sentinel.FlashLoanFeaturesR\tflashLoan\x12F\n" +
	"\x0estate_variance\x18\x02 \x01(\v2\x1f.sentinel.StateVarianceFeaturesR\rstateVariance\x126\n" +
	"\bbytecode\x18\x03 \x01(\v2\x1a.sentinel.BytecodeFeaturesR\bbytecode\x120\n" +
	"\x06opcode\x18\x04 \x01(\v2\x18.sentinel.OpcodeFeaturesR\x06opcode\"\xa8\x02\n" +
	"\x11FlashLoanFeatures\x12$\n" +
	"\x0ehas_flash_loan\x18\x01 \x01(\bR\fhasFlashLoan\x12(\n" +
	"\x10flash_loan_count\x18\x02 \x01(\x05R\x0eflashLoanCount\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x12%\n" +
	"\x0etotal_borrowed\x18\x04 \x01(\tR\rtotalBorrowed\x12!\n" +
	"\fhas_callback\x18\x05 \x01(\bR\vhasCallback\x12,\n" +
	"\x12nested_flash_loans\x18\x06 \x01(\bR\x10nestedFlashLoans\x12-\n" +
	"\x12repayment_detected\x18\a \x01(\bR\x11repaymentDetected\"\xec\x02\n" +
	"\x15StateVarianceFeatures\x122\n" +
	"\x15total_storage_changes\x18\x01 \x01(\x05R\x13totalStorageChanges\x12:\n" +
	"\x19unique_contracts_modified\x18\x02 \x01(\x05R\x17uniqueContractsModified\x122\n" +
	"\x15unique_slots_modified\x18\x03 \x01(\x05R\x13uniqueSlotsModified\x120\n" +
	"\x14balance_slot_changes\x18\x04 \x01(\x05R\x12balanceSlotChanges\x12.\n" +
	"\x13large_value_changes\x18\x05 \x01(\x05R\x11largeValueChanges\x12&\n" +
	"\x0fmax_value_delta\x18\x06 \x01(\tR\rmaxValueDelta\x12%\n" +
	"\x0evariance_ratio\x18\a \x01(\x01R\rvarianceRatio\"\x96\x04\n" +
	"\x10BytecodeFeatures\x12'\n" +
	"\x0fbytecode_length\x18\x01 \x01(\x05R\x0ebytecodeLength\x12\x1f\n" +
	"\vis_contract\x18\x02 \x01(\bR\n" +
	"isContract\x12\x19\n" +
	"\bis_proxy\x18\x03 \x01(\bR\aisProxy\x12\x1d\n" +
	"\n" +
	"proxy_type\x18\x04 \x01(\tR\tproxyType\x12.\n" +
	"\x13contract_age_blocks\x18\x05 \x01(\x05R\x11contractAgeBlocks\x12\x1f\n" +
	"\vis_verified\x18\x06 \x01(\bR\n" +
	"isVerified\x122\n" +
	"\x15matches_known_exploit\x18\a \x01(\bR\x13matchesKnownExploit\x12,\n" +
	"\x12matched_exploit_id\x18\b \x01(\tR\x10matchedExploitId\x12-\n" +
	"\x12jaccard_similarity\x18\t \x01(\x01R\x11jaccardSimilarity\x12)\n" +
	"\x10has_selfdestruct\x18\n" +
	" \x01(\bR\x0fhasSelfdestruct\x12)\n" +
	"\x10has_delegatecall\x18\v \x01(\bR\x0fhasDelegatecall\x12\x1f\n" +
	"\vhas_create2\x18\f \x01(\bR\n" +
	"hasCreate2\x12%\n" +
	"\x0eunique_opcodes\x18\r \x01(\x05R\runiqueOpcodes\"\xc2\x03\n" +
	"\x0eOpcodeFeatures\x12\x1f\n" +
	"\vtotal_calls\x18\x01 \x01(\x05R\n" +
	"totalCalls\x12\x1d\n" +
	"\n" +
	"call_depth\x18\x02 \x01(\x05R\tcallDepth\x12-\n" +
	"\x12delegatecall_count\x18\x03 \x01(\x05R\x11delegatecallCount\x12)\n" +
	"\x10staticcall_count\x18\x04 \x01(\x05R\x0fstaticcallCount\x12!\n" +
	"\fcreate_count\x18\x05 \x01(\x05R\vcreateCount\x12#\n" +
	"\rcreate2_count\x18\x06 \x01(\x05R\fcreate2Count\x12-\n" +
	"\x12selfdestruct_count\x18\a \x01(\x05R\x11selfdestructCount\x12%\n" +
	"\x0einternal_calls\x18\b \x01(\x05R\rinternalCalls\x12%\n" +
	"\x0eexternal_calls\x18\t \x01(\x05R\rexternalCalls\x12.\n" +
	"\x13gas_forwarded_ratio\x18\n" +
	" \x01(\x01R\x11gasForwardedRatio\x12!\n" +
	"\frevert_count\x18\v \x01(\x05R\vrevertCount\"S\n" +
	"\x13AnalyzeBatchRequest\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.sentinel.AnalyzeRequestR\ftransactions\"u\n" +
	"\x14AnalyzeBatchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.sentinel.AnalyzeResponseR\aresults\x12(\n" +
	"\x10total_latency_ms\x18\x02 \x01(\x01R\x0etotalLatencyMs\"\x0f\n" +
	"\rHealthRequest\"\xb4\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12&\n" +
	"\x0fmodel_loaded_at\x18\x03 \x01(\tR\rmodelLoadedAt\x12#\n" +
	"\rrpc_connected\x18\x04 \x01(\bR\frpcConnected\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\"\x0e\n" +
	"\fStatsRequest\"\xfe\x04\n" +
	"\rStatsResponse\x123\n" +
	"\x15transactions_analyzed\x18\x01 \x01(\x04R\x14transactionsAnalyzed\x12/\n" +
	"\x13suspicious_detected\x18\x02 \x01(\x04R\x12suspiciousDetected\x12/\n" +
	"\x13blocked_recommended\x18\x03 \x01(\x04R\x12blockedRecommended\x12,\n" +
	"\x12average_latency_ms\x18\x04 \x01(\x01R\x10averageLatencyMs\x12%\n" +
	"\x0emodel_accuracy\x18\x05 \x01(\x01R\rmodelAccuracy\x12.\n" +
	"\x13false_positive_rate\x18\x06 \x01(\x01R\x11falsePositiveRate\x12L\n" +
	"\rby_risk_level\x18\a \x03(\v2(.sentinel.StatsResponse.ByRiskLevelEntryR\vbyRiskLevel\x12H\n" +
	"\vby_protocol\x18\b \x03(\v2'.sentinel.StatsResponse.ByProtocolEntryR\n" +
	"byProtocol\x12:\n" +
	"\rrecent_alerts\x18\t \x03(\v2\x15.sentinel.RecentAlertR\frecentAlerts\x1a>\n" +
	"\x10ByRiskLevelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a=\n" +
	"\x0fByProtocolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xbd\x01\n" +
	"\vRecentAlert\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x122\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\x0e2\x13.sentinel.RiskLevelR\triskLevel\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12'\n" +
	"\x0frisk_indicators\x18\x05 \x03(\tR\x0eriskIndicators*m\n" +
	"\tRiskLevel\x12\x10\n" +
	"\fRISK_UNKNOWN\x10\x00\x12\r\n" +
	"\tRISK_SAFE\x10\x01\x12\f\n" +
	"\bRISK_LOW\x10\x02\x12\x0f\n" +
	"\vRISK_MEDIUM\x10\x03\x12\r\n" +
	"\tRISK_HIGH\x10\x04\x12\x11\n" +
	"\rRISK_CRITICAL\x10\x05*\x94\x01\n" +
	"\x0eRecommendation\x12\x1a\n" +
	"\x16RECOMMENDATION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14RECOMMENDATION_ALLOW\x10\x01\x12\x17\n" +
	"\x13RECOMMENDATION_FLAG\x10\x02\x12\x19\n" +
	"\x15RECOMMENDATION_REVIEW\x10\x03\x12\x18\n" +
	"\x14RECOMMENDATION_BLOCK\x10\x042\x9c\x02\n" +
	"\x11SentinelInference\x12>\n" +
	"\aAnalyze\x12\x18.sentinel.AnalyzeRequest\x1a\x19.sentinel.AnalyzeResponse\x12M\n" +
	"\fAnalyzeBatch\x12\x1d.sentinel.AnalyzeBatchRequest\x1a\x1e.sentinel.AnalyzeBatchResponse\x12;\n" +
	"\x06Health\x12\x17.sentinel.HealthRequest\x1a\x18.sentinel.HealthResponse\x12;\n" +
	"\bGetStats\x12\x16.sentinel.StatsRequest\x1a\x17.sentinel.StatsResponseB6Z4github.com/sentinel-protocol/sentinel-node/pkg/protob\x06proto3"

var (
	file_pkg_proto_sentinel_proto_rawDescOnce sync.Once
	file_pkg_proto_sentinel_proto_rawDescData []byte
)

func file_pkg_proto_sentinel_proto_rawDescGZIP() []byte {
	file_pkg_proto_sentinel_proto_rawDescOnce.Do(func() {
		file_pkg_proto_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_sentinel_proto_rawDesc), len(file_pkg_proto_sentinel_proto_rawDesc)))
	})
	return file_pkg_proto_sentinel_proto_rawDescData
}

var file_pkg_proto_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_sentinel_proto_goTypes = []any{
	(RiskLevel)(0),                // 0: sentinel.RiskLevel
	(Recommendation)(0),           // 1: sentinel.Recommendation
	(*AnalyzeRequest)(nil),        // 2: sentinel.AnalyzeRequest
	(*SimulationResult)(nil),      // 3: sentinel.SimulationResult
	(*StorageChange)(nil),         // 4: sentinel.StorageChange
	(*CallTrace)(nil),             // 5: sentinel.CallTrace
	(*AnalyzeResponse)(nil),       // 6: sentinel.AnalyzeResponse
	(*ProtocolContext)(nil),       // 7: sentinel.ProtocolContext
	(*FeatureBreakdown)(nil),      // 8: sentinel.FeatureBreakdown
	(*FlashLoanFeatures)(nil),     // 9: sentinel.FlashLoanFeatures
	(*StateVarianceFeatures)(nil), // 10: sentinel.StateVarianceFeatures
	(*BytecodeFeatures)(nil),      // 11: sentinel.BytecodeFeatures
	(*OpcodeFeatures)(nil),        // 12: sentinel.OpcodeFeatures
	(*AnalyzeBatchRequest)(nil),   // 13: sentinel.AnalyzeBatchRequest
	(*AnalyzeBatchResponse)(nil),  // 14: sentinel.AnalyzeBatchResponse
	(*HealthRequest)(nil),         // 15: sentinel.HealthRequest
	(*HealthResponse)(nil),        // 16: sentinel.HealthResponse
	(*StatsRequest)(nil),          // 17: sentinel.StatsRequest
	(*StatsResponse)(nil),         // 18: sentinel.StatsResponse
	(*RecentAlert)(nil),           // 19: sentinel.RecentAlert
	nil,                           // 20: sentinel.StatsResponse.ByRiskLevelEntry
	nil,                           // 21: sentinel.StatsResponse.ByProtocolEntry
}
var file_pkg_proto_sentinel_proto_depIdxs = []int32{
	3,  // 0: sentinel.AnalyzeRequest.simulation:type_name -> sentinel.SimulationResult
	4,  // 1: sentinel.SimulationResult.storage_changes:type_name -> sentinel.StorageChange
	5,  // 2: sentinel.SimulationResult.call_traces:type_name -> sentinel.CallTrace
	5,  // 3: sentinel.CallTrace.calls:type_name -> sentinel.CallTrace
	0,  // 4: sentinel.AnalyzeResponse.risk_level:type_name -> sentinel.RiskLevel
	1,  // 5: sentinel.AnalyzeResponse.recommendation:type_name -> sentinel.Recommendation
	7,  // 6: sentinel.AnalyzeResponse.protocol_context:type_name -> sentinel.ProtocolContext
	8,  // 7: sentinel.AnalyzeResponse.features:type_name -> sentinel.FeatureBreakdown
	9,  // 8: sentinel.FeatureBreakdown.flash_loan:type_name -> sentinel.FlashLoanFeatures
	10, // 9: sentinel.FeatureBreakdown.state_variance:type_name -> sentinel.StateVarianceFeatures
	11, // 10: sentinel.FeatureBreakdown.bytecode:type_name -> sentinel.BytecodeFeatures
	12, // 11: sentinel.FeatureBreakdown.opcode:type_name -> sentinel.OpcodeFeatures
	2,  // 12: sentinel.AnalyzeBatchRequest.transactions:type_name -> sentinel.AnalyzeRequest
	6,  // 13: sentinel.AnalyzeBatchResponse.results:type_name -> sentinel.AnalyzeResponse
	20, // 14: sentinel.StatsResponse.by_risk_level:type_name -> sentinel.StatsResponse.ByRiskLevelEntry
	21, // 15: sentinel.StatsResponse.by_protocol:type_name -> sentinel.StatsResponse.ByProtocolEntry
	19, // 16: sentinel.StatsResponse.recent_alerts:type_name -> sentinel.RecentAlert
	0,  // 17: sentinel.RecentAlert.risk_level:type_name -> sentinel.RiskLevel
	2,  // 18: sentinel.SentinelInference.Analyze:input_type -> sentinel.AnalyzeRequest
	13, // 19: sentinel.SentinelInference.AnalyzeBatch:input_type -> sentinel.AnalyzeBatchRequest
	15, // 20: sentinel.SentinelInference.Health:input_type -> sentinel.HealthRequest
	17, // 21: sentinel.SentinelInference.GetStats:input_type -> sentinel.StatsRequest
	6,  // 22: sentinel.SentinelInference.Analyze:output_type -> sentinel.AnalyzeResponse
	14, // 23: sentinel.SentinelInference.AnalyzeBatch:output_type -> sentinel.AnalyzeBatchResponse
	16, // 24: sentinel.SentinelInference.Health:output_type -> sentinel.HealthResponse
	18, // 25: sentinel.SentinelInference.GetStats:output_type -> sentinel.StatsResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_proto_sentinel_proto_init() }
func file_pkg_proto_sentinel_proto_init() {
	if File_pkg_proto_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_sentinel_proto_rawDesc), len(file_pkg_proto_sentinel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_sentinel_proto_goTypes,
		DependencyIndexes: file_pkg_proto_sentinel_proto_depIdxs,
		EnumInfos:         file_pkg_proto_sentinel_proto_enumTypes,
		MessageInfos:      file_pkg_proto_sentinel_proto_msgTypes,
	}.Build()
	File_pkg_proto_sentinel_proto = out.File
	file_pkg_proto_sentinel_proto_goTypes = nil
	file_pkg_proto_sentinel_proto_depIdxs = nil
}
