// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: pkg/proto/sentinel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentinelInference_Analyze_FullMethodName      = "/sentinel.SentinelInference/Analyze"
	SentinelInference_AnalyzeBatch_FullMethodName = "/sentinel.SentinelInference/AnalyzeBatch"
	SentinelInference_Health_FullMethodName       = "/sentinel.SentinelInference/Health"
	SentinelInference_GetStats_FullMethodName     = "/sentinel.SentinelInference/GetStats"
)

// SentinelInferenceClient is the client API for SentinelInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sentinel inference service for analyzing transactions
type SentinelInferenceClient interface {
	// Analyze a single pending transaction
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// Analyze a batch of transactions
	AnalyzeBatch(ctx context.Context, in *AnalyzeBatchRequest, opts ...grpc.CallOption) (*AnalyzeBatchResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Get model info and statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type sentinelInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelInferenceClient(cc grpc.ClientConnInterface) SentinelInferenceClient {
	return &sentinelInferenceClient{cc}
}

func (c *sentinelInferenceClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, SentinelInference_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelInferenceClient) AnalyzeBatch(ctx context.Context, in *AnalyzeBatchRequest, opts ...grpc.CallOption) (*AnalyzeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeBatchResponse)
	err := c.cc.Invoke(ctx, SentinelInference_AnalyzeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelInferenceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SentinelInference_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelInferenceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, SentinelInference_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentinelInferenceServer is the server API for SentinelInference service.
// All implementations must embed UnimplementedSentinelInferenceServer
// for forward compatibility.
//
// Sentinel inference service for analyzing transactions
type SentinelInferenceServer interface {
	// Analyze a single pending transaction
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// Analyze a batch of transactions
	AnalyzeBatch(context.Context, *AnalyzeBatchRequest) (*AnalyzeBatchResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Get model info and statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedSentinelInferenceServer()
}

// UnimplementedSentinelInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelInferenceServer struct{}

func (UnimplementedSentinelInferenceServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedSentinelInferenceServer) AnalyzeBatch(context.Context, *AnalyzeBatchRequest) (*AnalyzeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeBatch not implemented")
}
func (UnimplementedSentinelInferenceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSentinelInferenceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSentinelInferenceServer) mustEmbedUnimplementedSentinelInferenceServer() {}
func (UnimplementedSentinelInferenceServer) testEmbeddedByValue()                           {}

// UnsafeSentinelInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelInferenceServer will
// result in compilation errors.
type UnsafeSentinelInferenceServer interface {
	mustEmbedUnimplementedSentinelInferenceServer()
}

func RegisterSentinelInferenceServer(s grpc.ServiceRegistrar, srv SentinelInferenceServer) {
	// If the following call panics, it indicates UnimplementedSentinelInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentinelInference_ServiceDesc, srv)
}

func _SentinelInference_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelInferenceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelInference_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelInferenceServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelInference_AnalyzeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelInferenceServer).AnalyzeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelInference_AnalyzeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelInferenceServer).AnalyzeBatch(ctx, req.(*AnalyzeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelInference_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelInferenceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelInference_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelInferenceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelInference_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelInferenceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelInference_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelInferenceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentinelInference_ServiceDesc is the grpc.ServiceDesc for SentinelInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.SentinelInference",
	HandlerType: (*SentinelInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _SentinelInference_Analyze_Handler,
		},
		{
			MethodName: "AnalyzeBatch",
			Handler:    _SentinelInference_AnalyzeBatch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SentinelInference_Health_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _SentinelInference_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/sentinel.proto",
}
