name: Bug Report
description: Report a bug in Aegis Network
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the form below.

        **For security vulnerabilities, please see [SECURITY.md](../SECURITY.md) instead.**

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - sentinel-brain (Python)
        - sentinel-core (Solidity)
        - sentinel-node (Go)
        - Multiple packages
        - Not sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment details:
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14]
        - Python version: [e.g., 3.11]
        - Go version: [e.g., 1.22]
        - Foundry version: [e.g., 0.2.0]
        - Package version: [e.g., 0.1.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This is not a security vulnerability (see SECURITY.md)
          required: true
