# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sentinel_brain.grpc import sentinel_pb2 as sentinel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentinel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentinelInferenceStub(object):
    """Sentinel inference service for analyzing transactions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/sentinel.SentinelInference/Analyze',
                request_serializer=sentinel__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=sentinel__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.AnalyzeBatch = channel.unary_unary(
                '/sentinel.SentinelInference/AnalyzeBatch',
                request_serializer=sentinel__pb2.AnalyzeBatchRequest.SerializeToString,
                response_deserializer=sentinel__pb2.AnalyzeBatchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/sentinel.SentinelInference/Health',
                request_serializer=sentinel__pb2.HealthRequest.SerializeToString,
                response_deserializer=sentinel__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/sentinel.SentinelInference/GetStats',
                request_serializer=sentinel__pb2.StatsRequest.SerializeToString,
                response_deserializer=sentinel__pb2.StatsResponse.FromString,
                _registered_method=True)


class SentinelInferenceServicer(object):
    """Sentinel inference service for analyzing transactions
    """

    def Analyze(self, request, context):
        """Analyze a single pending transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeBatch(self, request, context):
        """Analyze a batch of transactions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get model info and statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentinelInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=sentinel__pb2.AnalyzeRequest.FromString,
                    response_serializer=sentinel__pb2.AnalyzeResponse.SerializeToString,
            ),
            'AnalyzeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBatch,
                    request_deserializer=sentinel__pb2.AnalyzeBatchRequest.FromString,
                    response_serializer=sentinel__pb2.AnalyzeBatchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sentinel__pb2.HealthRequest.FromString,
                    response_serializer=sentinel__pb2.HealthResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=sentinel__pb2.StatsRequest.FromString,
                    response_serializer=sentinel__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.SentinelInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.SentinelInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentinelInference(object):
    """Sentinel inference service for analyzing transactions
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelInference/Analyze',
            sentinel__pb2.AnalyzeRequest.SerializeToString,
            sentinel__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelInference/AnalyzeBatch',
            sentinel__pb2.AnalyzeBatchRequest.SerializeToString,
            sentinel__pb2.AnalyzeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelInference/Health',
            sentinel__pb2.HealthRequest.SerializeToString,
            sentinel__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelInference/GetStats',
            sentinel__pb2.StatsRequest.SerializeToString,
            sentinel__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
